# Generated by Django 5.0.1 on 2024-01-28 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asesor', '0002_alter_asesor_options'),
        ('viajero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'categoría de destino',
                'verbose_name_plural': 'categorías de destinos',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje', models.DateField(blank=True, null=True)),
                ('comision', models.FloatField()),
                ('fecha_actualizacion', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='fecha de actualización')),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asesor.asesor')),
                ('viajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viajero.viajero')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viaje.viajecategoria')),
            ],
            options={
                'verbose_name': 'viaje',
                'verbose_name_plural': 'viajes',
            },
        ),
    ]
