# Generated by Django 5.0.1 on 2024-01-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesor',
            options={'verbose_name': 'asesor', 'verbose_name_plural': 'asesores'},
        ),
    ]
