# Generated by Django 5.0.1 on 2024-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0002_asesor_estudiante_fecha_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='apellido',
            field=models.CharField(default='Perez', max_length=100),
            preserve_default=False,
        ),
    ]
