# Generated by Django 5.0.1 on 2024-01-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0003_asesor_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='estudianteporcurso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coder.viajero'),
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
