# Generated by Django 5.0.1 on 2024-01-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0006_viaje_fecha_viaje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsesorPorLugar',
            new_name='ViajePorAsesor',
        ),
        migrations.RenameField(
            model_name='viajeporasesor',
            old_name='lugar',
            new_name='viaje',
        ),
    ]
