# Generated by Django 5.0.1 on 2024-01-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0008_viaje_asesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViajePorAsesor',
        ),
    ]
