# Generated by Django 5.0.1 on 2024-01-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0009_delete_viajeporasesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='viajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coder.viajero'),
        ),
    ]
