# Generated by Django 5.0.1 on 2024-01-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0011_alter_viaje_asesor_alter_viaje_viajero_delete_asesor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
